# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  first-ppm:
    desc: Generate our first test ppm
    cmds:
      - go run ./src/first-ppm > ./ppm/first.ppm
