# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  first-ppm:
    desc: Generate our first test ppm
    cmds:
      - go run ./src/first-ppm

  cam-test:
    desc: Generate ppm via camera
    cmds:
      - go run ./src/cam-test

  test:
    desc: Run all library code tests
    cmds:
      - go test ./lib/**
